# Generated by Django 3.1 on 2020-08-23 18:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('gid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField()),
                ('tag_id', models.IntegerField()),
                ('length', models.FloatField()),
                ('length_m', models.FloatField()),
                ('name', models.TextField()),
                ('source', models.BigIntegerField()),
                ('target', models.BigIntegerField()),
                ('source_osm', models.BigIntegerField()),
                ('target_osm', models.BigIntegerField()),
                ('cost', models.FloatField()),
                ('reverse_cost', models.FloatField()),
                ('cost_s', models.FloatField()),
                ('reverse_cost_s', models.FloatField()),
                ('rule', models.TextField()),
                ('one_way', models.IntegerField()),
                ('oneway', models.TextField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('maxspeed_forward', models.FloatField()),
                ('maxspeed_backward', models.FloatField()),
                ('priority', models.FloatField()),
                ('the_geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'chicago_ways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('members', django.contrib.postgres.fields.hstore.HStoreField()),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('tag_name', models.TextField()),
                ('tag_value', models.TextField()),
                ('name', models.TextField()),
                ('the_geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'osm_ways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MellowWay',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('ways', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), help_text='Select one or more streets on the map to mark them as mellow. Add or remove a street by clicking on it, or remove all streets by clicking the "Clear all" button.', size=None)),
            ],
        ),
    ]
