# Generated by Django 3.1 on 2020-08-24 01:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mellow_bike_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mellowway',
            name='bounding_box',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
