# Generated by Django 3.1 on 2020-08-24 02:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellow_bike_map', '0002_mellowway_bounding_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mellowway',
            name='ways',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Select one or more streets on the map to mark them as mellow. Add or remove a street by clicking on it, or remove all streets by clicking the "Clear all" button.', size=None),
        ),
    ]
