# Generated by Django 3.1 on 2026-03-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mellowroute',
            name='type',
            field=models.CharField(choices=[('route', 'Official bike route'), ('street', 'Mellow street'), ('path', 'Off-street bike path'), ('sidewalk', 'Connecting sidewalk')], default='street', max_length=8),
        ),
    ]
