# Generated by Django 3.1 on 2026-03-15 16:25

from django.db import migrations


def create_sidewalks(apps, schema_editor):
    """Upgrade function: Create sidewalks for every existing neighborhood."""
    MellowRoute = apps.get_model('mbm', 'MellowRoute')
    existing_mellowroutes = MellowRoute.objects.distinct('slug').order_by('slug')
    new_mellowroutes = []
    for mellowroute in existing_mellowroutes:
        # Resetting the PK will force Django to copy the object. See:
        # https://docs.djangoproject.com/en/3.1/topics/db/queries/#copying-model-instances
        mellowroute.pk = None
        mellowroute.type = 'sidewalk'
        mellowroute.ways = []
        new_mellowroutes.append(mellowroute)

    # Bulk create objects so that we can create them in one write query
    MellowRoute.objects.bulk_create(new_mellowroutes)
    print(
        f'Created {len(new_mellowroutes)} new MellowRoute '
        f'object{"s" if len(new_mellowroutes) > 1 else ""} '
        f'with type "sidewalk" for {len(existing_mellowroutes)} existing '
        f'neighborhood{"s" if len(existing_mellowroutes) > 1 else ""}'
    )


def delete_sidewalks(apps, schema_editor):
    """Downgrade function: Delete all sidewalks."""
    MellowRoute = apps.get_model('mbm', 'MellowRoute')
    sidewalks = MellowRoute.objects.filter(type='sidewalk')
    count = sidewalks.count()
    sidewalks.delete()
    print(
        f'Deleted {count} MellowRoute '
        f'object{"s" if count != 1 else ""} '
        f'with type "sidewalk"'
    )
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mbm', '0002_add_mellowroute_type_sidewalk'),
    ]

    operations = [
        migrations.RunPython(create_sidewalks, reverse_code=delete_sidewalks)
    ]
