# Generated by Django 3.1 on 2026-03-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbm', '0004_add_clean_ways_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='edge',
            table='clean_ways',
        ),
    ]
