name: mellow-bike-map
region: tor

databases:
  - name: mellow-bike-map-db
    engine: PG
    production: true
    version: "16"

services:
  - name: mellow-bike-map-app
    github:
      repo: jeancochrane/mellow-bike-map
      branch: staging
      deploy_on_push: true

    dockerfile_path: Dockerfile

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${mellow-bike-map-db.DATABASE_URL}
      - key: DJANGO_DEBUG
        scope: RUN_TIME
        value: "True"
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_TIME
        value: ".ondigitalocean.app"
      - key: DJANGO_MANAGEPY_MIGRATE
        scope: RUN_TIME
        value: "on"
      - key: POSTGRES_REQUIRE_SSL
        scope: RUN_TIME
        value: "true"

    run_command: ./docker-entrypoint.sh python manage.py runserver 0.0.0.0:8000
