name: Test and deploy

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: reallysupersecret
      DJANGO_SETTINGS_MODULE: mbm.settings
      DB_HOST: localhost
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends gdal-bin
          pip install --upgrade pip
          pip install --upgrade -r app/requirements.txt
      - name: Run Python tests
        run: |
          cp -R tests app/tests
          cd app && pytest
      - name: Run JavaScript tests
        run: |
          cd app && npm test
  deploy:
    needs: test
    if: github.ref == env.PROD_REF || github.ref == env.STAGING_REF
    runs-on: ubuntu-latest
    environment: Dev
    env:
      AWS_REGION: us-east-2
      PROD_REF: refs/heads/master
      STAGING_REF: refs/heads/jeancochrane/setup-aws-staging-instance
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set deployment environment
        run: |
          if [ "$GITHUB_REF" == "$STAGING_REF" ]; then
            echo "APP_NAME=mellow-bike-map-staging" >> $GITHUB_ENV
            echo "DEPLOYMENT_GROUP=staging" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" == "$PROD_REF" ]; then
            echo "APP_NAME=mellow-bike-map" >> $GITHUB_ENV
            echo "DEPLOYMENT_GROUP=production" >> $GITHUB_ENV
          else
            echo "Error: unexpected ref '$GITHUB_REF', cancelling deployment"
            exit 1
          fi
      - name: Deploy app
        run: |
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment \
            --application-name "$APP_NAME" \
            --deployment-group-name "$DEPLOYMENT_GROUP" \
            --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash \
            --ignore-application-stop-failures
